name: "Events README"
description: "🗓 Generate a README.md summary for your events repository"
author: "Anand Chowdhary <https://github.com/AnandChowdhary>"
runs:
  using: "node12"
  main: "dist/index.js"
inputs:
  bot-name:
    required: false
    description: "Name for commit"
  bot-email:
    required: false
    description: "Email for commit"
branding:
  icon: "calendar"
  color: "green"
