name: Test CI
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test action
    runs-on: ubuntu-18.04
    if: "contains(github.event.head_commit.message, 'Deploy new version')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
